### ISSUE TITLE
Zotero 7 Icon is wrong

### ISSUE THREAD

**Issue by AAguiarCAM** [flathub/org.zotero.Zotero#172]
For some reason, the flatpak is using the symbolic icon in the gnome overview

https://imgur.com/a/XzLjIJr

https://imgur.com/a/Ri9eXOu

i thought it was a problem with Zotero 7 itself, but i just installed the tarball. the script in the folder ("set_launcher_icon"), that creates the .desktop file, is clearly pointing to the [actual new icon](https://github.com/zotero/zotero/blob/main/app/linux/icons/icon128.png)

**Comment by sebastian-de** [comment]
I thought this was fixed by https://github.com/flathub/org.zotero.Zotero/pull/139
No idea what else we can do here - any suggestions?

**Comment by AAguiarCAM** [comment]
no idea. i am just an overly curious lawyer.

but it does show the right icon in the activities 

![image](https://github.com/flathub/org.zotero.Zotero/assets/19801508/bd84a061-b4ac-4cd5-8300-661e3f1aa46e)

as you can see in the top, the panel shows the symbolic icon, and overview is still the same as the first image

![](https://imgur.com/nG05Yxq.png)

**Comment by AAguiarCAM** [comment]
the icon is also right in the Applications section of the Settings

![image](https://github.com/flathub/org.zotero.Zotero/assets/19801508/a06339f1-d527-44d1-aca9-0f338e1b6825)

**Comment by AAguiarCAM** [comment]
the icon wasnt really symbolic, as it didnot changed colors when i changed the theme. i fixed that by 

1. setting the fill of the svg to #000000 
2. i put the file in the icons/hicolor/scalable folder with -symbolic on the name.


All of that was [as advised by Gnome](https://wiki.gnome.org/HowDoI/CreateSymbolicIconsThatChangeColorAccordingToTheme)

that icon came from upstream, so the problem is probably there.

i am still trying to figure out how to make it the actual icon instead of the symbolic one

**Comment by iealexop** [comment]
Can confirm, this is also an issue on Cinnamon DE

**Comment by frederik-elwert** [comment]
Same on Ubuntu. In its vertical dock, with a dark background colour, the icon is almost invisible.

![grafik](https://github.com/user-attachments/assets/8933c429-28a6-4241-8b6e-5151a0da1288)

**Comment by sebastian-de** [comment]
I'll probably just remove the symbolic icon again, since it only causes problems.
